<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DSCHD-PC-CB-77" failures="0" tests="12" name="Test_site" time="2.873" errors="1" timestamp="25 Nov 2020 10:13:19 GMT" skipped="11">
  <testcase classname="Test_site" name="test_4" time="0.000">
    <skipped/>
  </testcase> <!-- test_4 -->
  <testcase classname="Test_site" name="test_2" time="0.000">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase classname="Test_site" name="test_1" time="0.000">
    <skipped/>
  </testcase> <!-- test_1 -->
  <testcase classname="Test_site" name="set_up" time="2.873">
    <error message="Failed to create an instance of io.testproject.sdk.drivers.web.ChromeDriver
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;DSCHD-PC-CB-77&#039;, ip: &#039;192.168.6.76&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;11.0.9&#039;
Driver info: driver.version: unknown" type="org.openqa.selenium.WebDriverException">
      <![CDATA[org.openqa.selenium.WebDriverException: Failed to create an instance of io.testproject.sdk.drivers.web.ChromeDriver
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DSCHD-PC-CB-77', ip: '192.168.6.76', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.9'
Driver info: driver.version: unknown
at io.testproject.sdk.DriverBuilder.build(DriverBuilder.java:194)
at Test_site.set_up(Test_site.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at io.testproject.sdk.DriverBuilder.build(DriverBuilder.java:186)
... 25 more
Caused by: io.testproject.sdk.internal.exceptions.AgentConnectException: Failed communicating with the Agent at http://192.168.6.144:8585
at io.testproject.sdk.internal.rest.AgentClient.startSession(AgentClient.java:468)
at io.testproject.sdk.internal.rest.AgentClient.<init>(AgentClient.java:229)
at io.testproject.sdk.internal.rest.AgentClient.getClient(AgentClient.java:401)
at io.testproject.sdk.drivers.web.ChromeDriver.<init>(ChromeDriver.java:367)
... 30 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.6.144:8585 [/192.168.6.144] failed: Connection refused: connect
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at io.testproject.sdk.internal.rest.AgentClient.startSession(AgentClient.java:466)
... 33 more
Caused by: java.net.ConnectException: Connection refused: connect
at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
at java.base/java.net.Socket.connect(Socket.java:608)
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
... 43 more
]]>
    </error>
  </testcase> <!-- set_up -->
  <testcase classname="Test_site" name="test_1" time="0.000">
    <skipped/>
  </testcase> <!-- test_1 -->
  <testcase classname="Test_site" name="test_5" time="0.000">
    <skipped/>
  </testcase> <!-- test_5 -->
  <testcase classname="Test_site" name="test_1" time="0.000">
    <skipped/>
  </testcase> <!-- test_1 -->
  <testcase classname="Test_site" name="test_2" time="0.000">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase classname="Test_site" name="test_5" time="0.000">
    <skipped/>
  </testcase> <!-- test_5 -->
  <testcase classname="Test_site" name="test_2" time="0.000">
    <skipped/>
  </testcase> <!-- test_2 -->
  <testcase classname="Test_site" name="test_3" time="0.000">
    <skipped/>
  </testcase> <!-- test_3 -->
  <testcase classname="Test_site" name="test_5" time="0.000">
    <skipped/>
  </testcase> <!-- test_5 -->
</testsuite> <!-- Test_site -->
